import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeSettings,collectContext,parseOptions,generateOptions,DraftSelection,waitForResult} from './generator.js';
test('settings migrate and bound values',()=>{const s=normalizeSettings({count:99,mode:'replace',depth:-1});assert.equal(s.count,6);assert.equal(s.depth,1);assert.equal(s.mode,'replace');assert.equal(s.expanded,false);});
test('context includes persona/card/group, filters system, respects switches and caps',()=>{const ctx={name1:'我',characterId:0,characters:[{name:'甲',avatar:'a',description:'设定'}],powerUserSettings:{persona_description:'人设'},chat:[{is_system:true,mes:'秘密'},{mes:'聊天'}]};const before=JSON.stringify(ctx);const c=collectContext(ctx,{world:true},[{content:'世界'}]);assert.equal(c.persona,'人设');assert.equal(c.characters[0].description,'设定');assert.equal(c.world[0].content,'世界');assert.equal(c.history.length,1);assert.equal(JSON.stringify(ctx),before);assert.equal(collectContext(ctx,{persona:false,character:false}).characters.length,0);ctx.groupId='g';ctx.groups=[{id:'g',members:['a']}];assert.equal(collectContext(ctx,{}).characters.length,1);});
test('parser tolerates prose fences and think blocks without executing HTML',()=>{const r=parseOptions('<think>reason</think>Here:\n```json\n{"options":[{"label":"方向","text":"<img src=x>"},"另一个","另一个"]}\n```');assert.equal(r.length,2);assert.equal(r[0].text,'<img src=x>');for(const s of ['null','{}','oops','{"options":["x","x"]}'])assert.throws(()=>parseOptions(s));});
test('adapter includes custom style, length, draft and directions',async()=>{let args;const r=await generateOptions({chat:[{mes:'Hi'}],generateRaw:async v=>{args=v;return '["A","B"]';}},{length:'long',style:'dialogue',prompt:'简洁',directions:'追问'},{draft:'拒绝'});assert.equal(r.length,2);for(const s of ['简洁','追问','拒绝','仅对白','3 至 6'])assert.ok(args.prompt.includes(s));});
function input(value='草稿'){return {value,events:[],dispatchEvent(e){this.events.push(e.type);},focus(){},setSelectionRange(){}};}
test('switch and undo preserve original; edits block destructive operation',()=>{const d=new DraftSelection(),i=input();d.choose(i,'A');d.choose(i,'B');assert.equal(i.value,'草稿\nB');d.undo(i);assert.equal(i.value,'草稿');d.choose(i,'A','replace');i.value+='编辑';assert.throws(()=>d.undo(i));assert.throws(()=>d.choose(i,'B'));d.reset();d.choose(i,'C');assert.equal(i.value,'A编辑\nC');assert.ok(i.events.every(e=>e==='input'));});
test('timeout, cancellation and rejection recover and swallow late output',async()=>{await assert.rejects(waitForResult(new Promise(()=>{}),5),/超时/);const a=new AbortController();const p=waitForResult(new Promise(()=>{}),100,a.signal);a.abort();await assert.rejects(p,/停止/);assert.equal(await waitForResult(Promise.resolve('ok'),100),'ok');await assert.rejects(waitForResult(Promise.reject(new Error('offline')),100),/offline/);});
class Element {constructor(tag){this.tag=tag;this.children=[];this.listeners={};this.value='';this.attrs={};this.textContent='';}append(...c){this.children.push(...c);}before(p){globalThis.panel=p;}addEventListener(e,f){this.listeners[e]=f;}setAttribute(k,v){this.attrs[k]=v;}replaceChildren(){this.children=[];}scrollIntoView(){}dispatchEvent(e){this.event=e.type;}focus(){}setSelectionRange(){}}
const find=(n,text)=>n.textContent===text?n:n.children.map(c=>find(c,text)).find(Boolean);
test('real UI handlers: generation, switching, undo, chat invalidation and retry',async()=>{const form=new Element(),i=input(),settingsHost=new Element(),handlers={};const ctx={chatId:'a',chat:[{mes:'hello'}],extensionSettings:{},eventTypes:{CHAT_CHANGED:'chat'},eventSource:{on:(e,f)=>handlers[e]=f},generateRaw:async()=> '["A","B"]'};globalThis.SillyTavern={getContext:()=>ctx};globalThis.document={readyState:'complete',getElementById:()=>null,createElement:t=>new Element(t),querySelector:s=>s==='#send_form'?form:s==='#send_textarea'?i:s==='#extensions_settings2'?settingsHost:null};await import('./index.js');const p=globalThis.panel;assert.equal(p.open,false);await find(p,'生成选项').listeners.click();const cards=p.children.find(c=>c.className==='ro-options');cards.children[0].listeners.click();cards.children[1].listeners.click();assert.equal(i.value,'草稿\nB');find(p,'撤销填入').listeners.click();assert.equal(i.value,'草稿');let resolve;ctx.generateRaw=()=>new Promise(r=>resolve=r);const pending=find(p,'生成 / 换一批').listeners.click();ctx.chatId='b';handlers.chat();resolve('["旧A","旧B"]');await pending;assert.equal(cards.children.length,0);ctx.generateRaw=async()=> '["新A","新B"]';await find(p,'生成 / 换一批').listeners.click();assert.equal(cards.children.length,2);assert.ok(i.events.every(e=>e==='input')); });


