import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeSettings,collectContext,parseOptions,generateOptions,DraftSelection,waitForResult} from './generator.js';
test('settings migrate and bound values',()=>{const s=normalizeSettings({count:99,mode:'replace',depth:-1});assert.equal(s.count,6);assert.equal(s.depth,1);assert.equal(s.mode,'replace');assert.equal(s.expanded,false);});
test('context includes persona/card/group, filters system, respects switches and caps',()=>{const ctx={name1:'我',characterId:0,characters:[{name:'甲',avatar:'a',description:'设定'}],powerUserSettings:{persona_description:'人设'},chat:[{is_system:true,mes:'秘密'},{mes:'聊天'}]};const before=JSON.stringify(ctx);const c=collectContext(ctx,{world:true},[{content:'世界'}]);assert.equal(c.persona,'人设');assert.equal(c.characters[0].description,'设定');assert.equal(c.world[0].content,'世界');assert.equal(c.history.length,1);assert.equal(JSON.stringify(ctx),before);assert.equal(collectContext(ctx,{persona:false,character:false}).characters.length,0);ctx.groupId='g';ctx.groups=[{id:'g',members:['a']}];assert.equal(collectContext(ctx,{}).characters.length,1);});
test('parser tolerates prose fences and think blocks without executing HTML',()=>{const r=parseOptions('<think>reason</think>Here:\n```json\n{"options":[{"label":"方向","text":"<img src=x>"},"另一个","另一个"]}\n```');assert.equal(r.length,2);assert.equal(r[0].text,'<img src=x>');for(const s of ['null','{}','oops','{"options":["x","x"]}'])assert.throws(()=>parseOptions(s));});
test('adapter includes custom style, length, draft and directions',async()=>{let args;const r=await generateOptions({worldInfoSettings:{},chat:[{mes:'Hi'}],generateRaw:async v=>{args=v;return '["A","B"]';}},{count:2,length:'long',style:'dialogue',prompt:'简洁',directions:'追问'},{draft:'拒绝'});assert.equal(r.length,2);for(const s of ['简洁','追问','拒绝','仅对白','3 至 6'])assert.ok(args.prompt.includes(s));});
function input(value='草稿'){return {value,events:[],dispatchEvent(e){this.events.push(e.type);},focus(){},setSelectionRange(){}};}
test('switch and undo preserve original; edits block destructive operation',()=>{const d=new DraftSelection(),i=input();d.choose(i,'A');d.choose(i,'B');assert.equal(i.value,'草稿\nB');d.undo(i);assert.equal(i.value,'草稿');d.choose(i,'A','replace');i.value+='编辑';assert.throws(()=>d.undo(i));assert.throws(()=>d.choose(i,'B'));d.reset();d.choose(i,'C');assert.equal(i.value,'A编辑\nC');assert.ok(i.events.every(e=>e==='input'));});
test('timeout, cancellation and rejection recover and swallow late output',async()=>{await assert.rejects(waitForResult(new Promise(()=>{}),5),/超时/);const a=new AbortController();const p=waitForResult(new Promise(()=>{}),100,a.signal);a.abort();await assert.rejects(p,/停止/);assert.equal(await waitForResult(Promise.resolve('ok'),100),'ok');await assert.rejects(waitForResult(Promise.reject(new Error('offline')),100),/offline/);});
class Element {constructor(tag){this.tag=tag;this.children=[];this.listeners={};this.value='';this.attrs={};this.textContent='';}append(...c){this.children.push(...c);}before(p){globalThis.panel=p;}addEventListener(e,f){this.listeners[e]=f;}setAttribute(k,v){this.attrs[k]=v;}replaceChildren(){this.children=[];}scrollIntoView(){}dispatchEvent(e){this.event=e.type;}focus(){}setSelectionRange(){}}
const find=(n,text)=>n.textContent===text?n:n.children.map(c=>find(c,text)).find(Boolean);
test('real UI handlers: generation, switching, undo, chat invalidation and retry',async()=>{const form=new Element(),i=input(),settingsHost=new Element(),handlers={};const ctx={worldInfoSettings:{},chatId:'a',chat:[{mes:'hello'}],extensionSettings:{reply_options_mvp:{count:2}},eventTypes:{CHAT_CHANGED:'chat'},eventSource:{on:(e,f)=>handlers[e]=f},generateRaw:async()=> '["A","B"]'};globalThis.SillyTavern={getContext:()=>ctx};globalThis.document={readyState:'complete',getElementById:()=>null,createElement:t=>new Element(t),querySelector:s=>s==='#send_form'?form:s==='#send_textarea'?i:s==='#extensions_settings2'?settingsHost:null};await import('./index.js');const p=globalThis.panel;assert.equal(p.open,false);await find(p,'生成选项').listeners.click();const cards=p.children.find(c=>c.className==='ro-options');cards.children[0].listeners.click();cards.children[1].listeners.click();assert.equal(i.value,'草稿\nB');find(p,'撤销填入').listeners.click();assert.equal(i.value,'草稿');let resolve;ctx.generateRaw=()=>new Promise(r=>resolve=r);const pending=find(p,'生成 / 换一批').listeners.click();while(!resolve) await new Promise(r=>setTimeout(r,0));ctx.chatId='b';handlers.chat();resolve('["旧A","旧B"]');await pending;assert.equal(cards.children.length,0);ctx.generateRaw=async()=> '["新A","新B"]';await find(p,'生成 / 换一批').listeners.click();assert.equal(cards.children.length,2);assert.ok(i.events.every(e=>e==='input')); });


import { readWorldContext } from './world-context.js';
test('character lore includes main, extra, embedded and group bindings without world toggle',async()=>{const calls=[];const ctx={characterId:0,characters:[{name:'A',avatar:'a.png',data:{extensions:{world:'main'}}}],loadWorldInfo:async name=>{calls.push(name);return {entries:{0:{content:name},1:{disable:true,content:'disabled'},2:{content:''}}};}};const before=JSON.stringify(ctx);const result=await readWorldContext(ctx,{character:true,world:false},()=>({world_info:{globalSelect:['unrelated'],charLore:[{name:'a',extraBooks:['extra','main']}]}}));assert.deepEqual(calls,['main','extra']);assert.deepEqual(result.entries.map(e=>e.content),['main','extra']);assert.equal(JSON.stringify(ctx),before);ctx.groupId='g';ctx.groups=[{id:'g',members:['a.png','b.png']}];ctx.characters.push({name:'B',avatar:'b.png',data:{character_book:{entries:[{enabled:true,content:'embedded'},{enabled:false,content:'off'}]}}});assert.ok((await readWorldContext(ctx,{character:true,world:false},()=>({}))).entries.some(e=>e.content==='embedded'));});
test('all selected books deduplicate scopes, retain complete content, exclude unselected books',async()=>{const calls=[];const ctx={characterId:0,characters:[{avatar:'a.png',data:{extensions:{world:'shared'}}}],chatMetadata:{world_info:'chat'},powerUserSettings:{persona_description_lorebook:'persona'},loadWorldInfo:async name=>{calls.push(name);return {entries:Array.from({length:45},(_,i)=>({uid:i,content:'x'.repeat(1600)}))};}};const result=await readWorldContext(ctx,{character:false,world:true},()=>({world_info:{globalSelect:['shared','global']}}));assert.deepEqual(calls,['shared','global','chat','persona']);assert.equal(result.entries.length,180);const data=collectContext(ctx,{character:false,world:true},result.entries);assert.equal(data.world.length,180);assert.equal(data.world[0].content.length,1600);assert.deepEqual(await readWorldContext(ctx,{character:false,world:false}),{entries:[],books:[]});});
test('book read failure is explicit and stale loading cannot start a model call',async()=>{await assert.rejects(readWorldContext({characters:[{data:{extensions:{world:'missing'}}}],characterId:0,loadWorldInfo:async()=>null},{character:true},()=>({})),/missing/);let called=false;await assert.rejects(generateOptions({worldInfoSettings:{},chat:[{mes:'x'}],generateRaw:async()=>{called=true;}},{},{isCurrent:()=>false}),/取消/);assert.equal(called,false);});
import { sampleDirections } from './generator.js';
test('direction sampling: fewer with replacement, more without replacement, equal covers pool',()=>{assert.deepEqual(sampleDirections('A\nB',4,()=>0),['A','A','A','A']);const r=sampleDirections('A\nB\nC\nD',3,()=>0.5);assert.equal(r.length,3);assert.equal(new Set(r).size,3);assert.deepEqual(new Set(sampleDirections('A\nB\nC',3)),new Set(['A','B','C']));assert.deepEqual(sampleDirections(' A \n\nA\n',3),['A','A','A']);assert.throws(()=>sampleDirections(' \n',3),/至少/);});
test('strict output count preserves direction slots and rejects missing, excess or duplicate replies',()=>{const dirs=['追问','追问','拒绝'];const raw='{"options":[{"label":"invented","text":"A"},"B","C"]}';assert.deepEqual(parseOptions(raw,3,dirs).map(x=>x.label),dirs);for(const bad of ['["A","B"]','["A","B","C","D"]','["A","A","B"]','["A",{},"B"]'])assert.throws(()=>parseOptions(bad,3,dirs),/恰好 3/);});
test('generation uses sampled directions and rejects undersized result',async()=>{let prompt;const ctx={worldInfoSettings:{},chat:[{mes:'hi'}],generateRaw:async args=>{prompt=args.prompt;return '["A","B","C"]';}};const r=await generateOptions(ctx,{count:3,directions:'追问'});assert.deepEqual(r.map(x=>x.label),['追问','追问','追问']);assert.ok(prompt.includes('["追问","追问","追问"]'));ctx.generateRaw=async()=> '["A","B"]';await assert.rejects(generateOptions(ctx,{count:3,directions:'追问'}),/恰好 3/);});
